# create the class for holding all the data associated with each design. 
# use namedtuple for memory for for what is parsed from spreedsheets and 
# fold data generated by nupack as should not change
from decimal import Decimal
from tokenize import Double
from turtle import st
from typing import Dict, NamedTuple
from unicodedata import decimal

class WetlabData(NamedTuple):
    eternaScore: float
    baselineSubscore: float
    foldingSubscore: float
    switchSubscore:float
    clusterNum: int
    foldChange: float
    foldChangeErrFactor: float
    KDOFF: float
    KDON: float
    ddG: float
    ddG_err: float

class NupackFoldData(NamedTuple):
    name: list


class DesignData(NamedTuple):
    sequence: str
    sequenceLength: int
    designID: int
    designName: str
    playerName: str
    wetlabResults: WetlabData
    nupackFoldResults: NupackFoldData
    
    

class puzzleData(NamedTuple):
    puzzleName: str
    designIdDict: dict[str, DesignData]


class RoundData(NamedTuple):
    roundName: str
    puzzleNameDict: dict[str, puzzleData]

       


